[env]
ALICE_MNEMONIC = "what close joke frequent rookie afraid lobster raise punch cluster industry talent render game stage ski math success rail elder critic negative there swap"
BOB_MNEMONIC = "hockey clever provide steel bachelor escape deal mansion dirt drift trouble coach setup tape chuckle report kangaroo concert congress first differ dragon hurry stamp"
